version: "3.0"

services:
  app:
    build: .
    container_name: app_workshop
    restart: always
    ports: 
      - 5555:5555
    volumes:
      - .:/first
    links:
      - database
    depends_on:
      - database
    
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database_mssql
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=36639821@Gui